Description: >
    Rajat Sharma / Udacity BertelsMann Scholar
    This template is to create a Networking Infra.
Resources:
    VPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: 10.0.0.0/16
            EnableDnsHostnames: true

